# Generated by Django 4.2.30 on 2026-07-08 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orphanages', '0009_alter_orphanage_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('child', 'Profil Enfant'), ('project', 'Projet de Financement'), ('orphanage_need', 'Besoin Orphelinat'), ('campaign', 'Campagne Fédération'), ('emergency', 'Urgence'), ('education', 'Éducation'), ('healthcare', 'Santé')], max_length=30, verbose_name="Type d'opportunité")),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Résumé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunities/', verbose_name='Image')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('funding', 'En recherche de financement'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('expired', 'Expiré')], default='published', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('normal', 'Normale'), ('urgent', 'Urgente'), ('critical', 'Critique')], default='normal', max_length=10, verbose_name='Priorité')),
                ('funding_goal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Objectif de financement')),
                ('current_funding', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Financement actuel')),
                ('beneficiary_count', models.IntegerField(default=0, verbose_name='Nombre de bénéficiaires')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Étiquettes')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('orphanage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='orphanages.orphanage', verbose_name='Orphelinat')),
                ('related_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Opportunité',
                'verbose_name_plural': 'Opportunités',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['type', 'status'], name='opportuniti_type_41b931_idx'), models.Index(fields=['priority', 'status'], name='opportuniti_priorit_08e51b_idx'), models.Index(fields=['created_at'], name='opportuniti_created_5f72d6_idx')],
            },
        ),
    ]
