# Generated by Django 4.2.30 on 2026-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Images supplémentaires'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='videos',
            field=models.JSONField(blank=True, default=list, verbose_name='Vidéos'),
        ),
    ]
