# Generated by Django 4.2.30 on 2026-06-15 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('country', models.CharField(choices=[('AO', 'Angola'), ('BJ', 'Bénin'), ('BW', 'Botswana'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CM', 'Cameroun'), ('CV', 'Cap-Vert'), ('CF', 'République centrafricaine'), ('KM', 'Comores'), ('CG', 'Congo-Brazzaville'), ('CD', 'République démocratique du Congo'), ('CI', "Côte d'Ivoire"), ('DJ', 'Djibouti'), ('EG', 'Égypte'), ('GQ', 'Guinée équatoriale'), ('ER', 'Érythrée'), ('SZ', 'Eswatini'), ('ET', 'Éthiopie'), ('GA', 'Gabon'), ('GM', 'Gambie'), ('GH', 'Ghana'), ('GN', 'Guinée'), ('GW', 'Guinée-Bissau'), ('KE', 'Kenya'), ('LS', 'Lesotho'), ('LR', 'Libéria'), ('LY', 'Libye'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('ML', 'Mali'), ('MR', 'Mauritanie'), ('MU', 'Maurice'), ('MA', 'Maroc'), ('MZ', 'Mozambique'), ('NA', 'Namibie'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('RW', 'Rwanda'), ('ST', 'Sao Tomé-et-Principe'), ('SN', 'Sénégal'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SO', 'Somalie'), ('ZA', 'Afrique du Sud'), ('SS', 'Soudan du Sud'), ('SD', 'Soudan'), ('TZ', 'Tanzanie'), ('TG', 'Togo'), ('TN', 'Tunisie'), ('UG', 'Ouganda'), ('ZM', 'Zambie'), ('ZW', 'Zimbabwe')], max_length=2, verbose_name='Pays')),
                ('role', models.CharField(choices=[('ambassador', 'Ambassadeur'), ('supermaster', 'Super Master'), ('partner', 'Partenaire'), ('director', "Chef d'orphelinat")], max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=False, verbose_name='Compte activé')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('email_verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
    ]
