# Generated by Django 4.2.30 on 2026-06-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanages', '0001_initial'),
        ('accounts', '0002_alter_user_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orphanage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='orphanages.orphanage', verbose_name='Orphelinat affilié'),
        ),
    ]
