# Generated by Django 4.2.30 on 2026-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_orphanage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ambassador", "Ambassadeur"),
                    ("federation", "Administrateur Federation"),
                    ("supermaster", "Super Master"),
                    ("partner", "Partenaire"),
                    ("director", "Chef d'orphelinat"),
                ],
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
