# Generated by Django 4.2.30 on 2026-07-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ambassador', 'Ambassadeur'), ('federation', 'Administrateur Federation'), ('supermaster', 'Super Master'), ('partner', 'Partenaire'), ('director', "Chef d'orphelinat"), ('auditor', 'Auditeur'), ('sponsor', 'Parrain/Marraine'), ('staff', 'Personnel Orphelinat')], max_length=20, verbose_name='Rôle'),
        ),
    ]
