# Generated by Django 4.2.30 on 2026-07-06 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='#', max_length=10, verbose_name='Icône')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('kind', models.CharField(choices=[('public', 'Public'), ('role', 'Réservé à un rôle'), ('emergency', 'Urgences'), ('announcement', 'Annonces'), ('project', 'Projet')], default='public', max_length=20, verbose_name='Type')),
                ('allowed_roles', models.JSONField(blank=True, default=list, verbose_name='Rôles autorisés')),
                ('post_roles', models.JSONField(blank=True, default=list, verbose_name='Rôles publieurs')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canaux',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.channel', verbose_name='Canal')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message de canal',
                'verbose_name_plural': 'Messages de canaux',
                'ordering': ['created_at'],
            },
        ),
    ]
