# Generated by Django 4.2.30 on 2026-07-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_channelmessage_edited_channelreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='channel_files/%Y/%m/', verbose_name='Fichier')),
                ('original_name', models.CharField(max_length=255, verbose_name="Nom d'origine")),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('mime', models.CharField(blank=True, max_length=120, verbose_name='Type MIME')),
                ('kind', models.CharField(default='file', max_length=20, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.channelmessage', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
    ]
