# Generated by Django 4.2.30 on 2026-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_channelattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='visibility_mode',
            field=models.CharField(choices=[('open', 'Ouvert'), ('role_filtered', 'Filtré par rôle'), ('private', 'Privé')], default='open', max_length=20, verbose_name='Mode de visibilité'),
        ),
    ]
