# Generated by Django 4.2.30 on 2026-07-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_replies_dm_attachments_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Modifié'),
        ),
    ]
