# Generated by Django 4.2.30 on 2026-06-24 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'orphelinat")),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('capacity', models.IntegerField(default=0, verbose_name="Capacité d'accueil")),
                ('status', models.CharField(default='active', max_length=50, verbose_name='Statut')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_orphanages', to=settings.AUTH_USER_MODEL, verbose_name='Ambassadeur')),
                ('director', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orphanage', to=settings.AUTH_USER_MODEL, verbose_name='Directeur')),
            ],
            options={
                'verbose_name': 'Orphelinat',
                'verbose_name_plural': 'Orphelinats',
            },
        ),
    ]
