# Generated by Django 4.2.30 on 2026-06-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanages', '0002_validation_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Feedback ambassadeur'),
        ),
        migrations.AlterField(
            model_name='orphanage',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente du federation'), ('active', "Accepté - en attente d'ambassadeur"), ('under_review', 'En cours de vérification'), ('changes_requested', 'Modifications demandées'), ('approved', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=50, verbose_name='Statut'),
        ),
    ]
