# Generated by Django 4.2.30 on 2026-06-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanages', '0003_orphanage_feedback_alter_orphanage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orphanage',
            name='ambassador',
        ),
        migrations.RemoveField(
            model_name='orphanage',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='orphanage',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=50, verbose_name='Statut'),
        ),
    ]
