# Generated by Django 4.2.30 on 2026-06-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanages', '0004_remove_orphanage_ambassador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage',
            name='annual_report',
            field=models.FileField(blank=True, null=True, upload_to='orphanage_docs/'),
        ),
        migrations.AddField(
            model_name='orphanage',
            name='child_protection',
            field=models.FileField(blank=True, null=True, upload_to='orphanage_docs/'),
        ),
        migrations.AddField(
            model_name='orphanage',
            name='director_id_doc',
            field=models.FileField(blank=True, null=True, upload_to='orphanage_docs/', verbose_name='Director ID document'),
        ),
        migrations.AddField(
            model_name='orphanage',
            name='ngo_accreditation',
            field=models.FileField(blank=True, null=True, upload_to='orphanage_docs/'),
        ),
        migrations.AddField(
            model_name='orphanage',
            name='operating_license',
            field=models.FileField(blank=True, null=True, upload_to='orphanage_docs/'),
        ),
        migrations.AddField(
            model_name='orphanage',
            name='partnership_certs',
            field=models.FileField(blank=True, null=True, upload_to='orphanage_docs/'),
        ),
        migrations.AddField(
            model_name='orphanage',
            name='registration_cert',
            field=models.FileField(blank=True, null=True, upload_to='orphanage_docs/'),
        ),
        migrations.AddField(
            model_name='orphanage',
            name='tax_doc',
            field=models.FileField(blank=True, null=True, upload_to='orphanage_docs/'),
        ),
    ]
