# Generated by Django 4.2.30 on 2026-06-30 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orphanages', '0005_orphanage_annual_report_orphanage_child_protection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Clé')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('required', models.BooleanField(default=True, verbose_name='REQUIS')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='OrphanageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orphanage_docs/', verbose_name='Fichier')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('changes_requested', 'Modifications demandées'), ('rejected', 'Refusé')], default='pending', max_length=30, verbose_name='Statut')),
                ('feedback', models.TextField(blank=True, verbose_name='Retour')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Révisé le')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Téléversé le')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanages.documenttype', verbose_name='Type de document')),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_documents', to='orphanages.orphanage')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Révisé par')),
            ],
            options={
                'verbose_name': "Document d'orphelinat",
                'verbose_name_plural': "Documents d'orphelinat",
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
