# Generated by Django 4.2.30 on 2026-06-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanages', '0007_seed_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanagedocument',
            name='points_to_update',
            field=models.TextField(blank=True, verbose_name='Points à corriger'),
        ),
    ]
