# Generated by Django 4.2.30 on 2026-07-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanages', '0008_orphanagedocument_points_to_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanage',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validé'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu'), ('archived', 'Archivé')], default='pending', max_length=50, verbose_name='Statut'),
        ),
    ]
