# Generated by Django 4.2.30 on 2026-06-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_child_orphanage'),
        ('publications', '0002_storyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audience',
            field=models.CharField(choices=[('general', 'Général'), ('child_info', 'Information Enfant')], default='general', max_length=20, verbose_name='Audience'),
        ),
        migrations.AddField(
            model_name='post',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='children.child', verbose_name='Enfant concerné'),
        ),
        migrations.AddField(
            model_name='post',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Raison du refus'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='approved', max_length=20, verbose_name='Statut'),
        ),
    ]
