# Generated by Django 4.2.30 on 2026-07-06 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0004_update_post_audience_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_ambassador',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ambassador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_to_review', to=settings.AUTH_USER_MODEL, verbose_name='Ambassadeur validateur'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('needs_changes', 'Modifications demandées')], default='approved', max_length=20, verbose_name='Statut'),
        ),
    ]
