# Generated by Django 4.2.30 on 2026-07-09 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0006_postdislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Modifié'),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenu'),
        ),
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('copy', 'Lien copié'), ('internal', 'Partage interne'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('x', 'X (Twitter)')], default='copy', max_length=20, verbose_name='Méthode')),
                ('destination', models.CharField(blank=True, max_length=120, verbose_name='Destination')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Partagé le')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='publications.post', verbose_name='Publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_shares', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Partage',
                'verbose_name_plural': 'Partages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comment_files/%Y/%m/', verbose_name='Fichier')),
                ('original_name', models.CharField(max_length=255, verbose_name="Nom d'origine")),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('mime', models.CharField(blank=True, max_length=120, verbose_name='Type MIME')),
                ('kind', models.CharField(default='file', max_length=20, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='publications.comment', verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Pièce jointe (commentaire)',
                'verbose_name_plural': 'Pièces jointes (commentaires)',
            },
        ),
    ]
