# Generated by Django 4.2.30 on 2026-07-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_project_source_update'),
        ('publications', '0007_comments_attachments_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='projets.project', verbose_name='Projet lié'),
        ),
    ]
