# Generated by Django 4.2.30 on 2026-06-24 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0005_child_orphanage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_type', models.CharField(choices=[('monthly', 'Mensuel'), ('annual', 'Annuel')], default='monthly', max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('paused', 'En pause'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='children.child', verbose_name='Enfant parrainé')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL, verbose_name='Parrain/Marraine')),
            ],
            options={
                'verbose_name': 'Parrainage',
                'verbose_name_plural': 'Parrainages',
                'unique_together': {('sponsor', 'child')},
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date du paiement')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Numéro de transaction')),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sponsorships.sponsorship', verbose_name='Parrainage')),
            ],
            options={
                'verbose_name': 'Paiement de parrainage',
                'verbose_name_plural': 'Paiements de parrainage',
                'ordering': ['-date'],
            },
        ),
    ]
