# Generated by Django 4.2.30 on 2026-06-24 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orphanages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, verbose_name='Source (Dons, Subventions...)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('date', models.DateField(auto_now_add=True)),
                ('orphanage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orphanages.orphanage')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie (Alimentation, Santé...)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('orphanage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orphanages.orphanage')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('financier', 'Financier'), ('materiel', 'Matériel'), ('service', 'Service')], max_length=20, verbose_name='Type de don')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Devise')),
                ('description', models.TextField(blank=True, verbose_name='Description (matériel/service)')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Numéro de transaction')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('donator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Donateur')),
                ('orphanage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_received', to='orphanages.orphanage', verbose_name='Orphelinat bénéficiaire')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
            },
        ),
    ]
