# Generated by Django 4.2.30 on 2026-07-08 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('orphanages', '0009_alter_orphanage_status'),
        ('projets', '0002_project_followers'),
        ('children', '0009_child_biography_child_dream_child_followers_and_more'),
        ('finances', '0002_donation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money')], max_length=50, unique=True, verbose_name='Provider')),
                ('display_name', models.CharField(max_length=100, verbose_name='Nom affiché')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur de paiement',
                'verbose_name_plural': 'Fournisseurs de paiement',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='children.child', verbose_name='Enfant bénéficiaire'),
        ),
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='projets.project', verbose_name='Projet bénéficiaire'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('donation', 'Don'), ('sponsorship', 'Parrainage'), ('project_financing', 'Financement de projet'), ('healthcare', 'Santé'), ('education', 'Éducation')], max_length=30, verbose_name='Type de transaction')),
                ('beneficiary_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Devise')),
                ('payment_method', models.CharField(choices=[('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire')], max_length=20, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('reference_number', models.CharField(max_length=255, unique=True, verbose_name='Numéro de référence')),
                ('provider_reference', models.CharField(blank=True, max_length=255, verbose_name='Référence fournisseur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('beneficiary_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('orphanage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orphanages.orphanage', verbose_name='Orphelinat')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Payeur')),
                ('payment_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.paymentprovider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='linked_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='finances.transaction', verbose_name='Transaction liée'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payer', '-created_at'], name='finances_tr_payer_i_d36743_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='finances_tr_transac_daf8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_number'], name='finances_tr_referen_11e994_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['beneficiary_content_type', 'beneficiary_object_id'], name='finances_tr_benefic_d5978d_idx'),
        ),
    ]
