# Generated by Django 4.2.30 on 2026-06-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='child',
            name='nationalite',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='child',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='child',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='child',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Sexe'),
        ),
    ]
