# Generated by Django 4.2.30 on 2026-06-24 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0002_alter_child_date_naissance_alter_child_nationalite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('health', 'Santé'), ('education', 'Éducation'), ('family', 'Famille'), ('documents', 'Documents'), ('social', 'Social')], max_length=20, verbose_name='Catégorie')),
                ('update_type', models.CharField(max_length=50, verbose_name='Type de mise à jour')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('previous_value', models.TextField(blank=True, default='', verbose_name='Ancienne valeur')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='Nouvelle valeur')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Raison')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Pièces jointes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='children.child', verbose_name='Enfant')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_updates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Mise à jour enfant',
                'verbose_name_plural': 'Mises à jour enfants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Création'), ('updated', 'Modification'), ('update_added', 'Mise à jour ajoutée'), ('document_added', 'Document ajouté'), ('document_verified', 'Document vérifié'), ('health_update', 'Mise à jour santé'), ('education_update', 'Mise à jour éducation'), ('family_update', 'Mise à jour famille'), ('social_update', 'Mise à jour sociale'), ('status_change', 'Changement de statut'), ('note_added', 'Note ajoutée')], max_length=30, verbose_name="Type d'événement")),
                ('category', models.CharField(choices=[('general', 'Général'), ('health', 'Santé'), ('education', 'Éducation'), ('family', 'Famille'), ('documents', 'Documents'), ('social', 'Social')], default='general', max_length=20, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='Ancienne valeur')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='Nouvelle valeur')),
                ('performed_role', models.CharField(blank=True, default='', max_length=50, verbose_name='Rôle')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='Département')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Pièces jointes')),
                ('event_date', models.DateTimeField(verbose_name="Date de l'événement")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='children.child', verbose_name='Enfant')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_history', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
            ],
            options={
                'verbose_name': 'Historique enfant',
                'verbose_name_plural': 'Historiques enfants',
                'ordering': ['-event_date'],
            },
        ),
    ]
