# Generated by Django 4.2.30 on 2026-06-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_childupdate_childhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('sick', 'Malade'), ('hospitalized', 'Hospitalisé'), ('healthy', 'En bonne santé'), ('enrolled', 'Scolarisé'), ('dropped_out', 'Déscolarisé'), ('with_guardian', 'Chez le tuteur'), ('missing', 'Disparu'), ('at_risk', 'À risque'), ('reunified', 'Réunifié'), ('adopted', 'Adopté'), ('transferred', 'Transféré'), ('exited', 'Sorti'), ('deceased', 'Décédé')], default='active', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='linked_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to='children.childupdate', verbose_name='Mise à jour liée'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], default='normal', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='Raison'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='source_module',
            field=models.CharField(choices=[('registration', 'Enregistrement'), ('child_profile', 'Profil enfant'), ('health', 'Santé'), ('education', 'Éducation'), ('family', 'Famille'), ('documents', 'Documents'), ('social', 'Social'), ('update_center', 'Centre de mise à jour'), ('status', 'Statut'), ('system', 'Système'), ('alert', 'Alerte'), ('follow_up', 'Suivi')], default='system', max_length=20, verbose_name='Module source'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='status_after',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Statut après'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='status_before',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Statut avant'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Sous-catégorie'),
        ),
        migrations.AlterField(
            model_name='childhistory',
            name='category',
            field=models.CharField(choices=[('general', 'Général'), ('registration', 'Enregistrement'), ('identity', 'Identité'), ('status', 'Statut'), ('health', 'Santé'), ('education', 'Éducation'), ('family', 'Famille'), ('documents', 'Documents'), ('social', 'Social'), ('protection', 'Protection'), ('alert', 'Alerte'), ('system', 'Système'), ('follow_up', 'Suivi')], default='general', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='childhistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'Création'), ('updated', 'Modification'), ('update_added', 'Mise à jour ajoutée'), ('document_added', 'Document ajouté'), ('document_verified', 'Document vérifié'), ('document_replaced', 'Document remplacé'), ('document_expired', 'Document expiré'), ('health_update', 'Mise à jour santé'), ('vaccination_added', 'Vaccination ajoutée'), ('illness_added', 'Maladie ajoutée'), ('treatment_started', 'Traitement commencé'), ('treatment_ended', 'Traitement terminé'), ('consultation_added', 'Consultation ajoutée'), ('hospitalization_added', 'Hospitalisation ajoutée'), ('allergy_added', 'Allergie ajoutée'), ('education_update', 'Mise à jour éducation'), ('school_enrolled', 'Inscription scolaire'), ('school_changed', "Changement d'école"), ('grade_added', 'Note ajoutée'), ('exam_result_added', 'Résultat examen ajouté'), ('family_update', 'Mise à jour famille'), ('guardian_assigned', 'Tuteur attribué'), ('parent_identified', 'Parent identifié'), ('family_reunified', 'Réunification familiale'), ('foster_placement', 'Placement familial'), ('adoption_progress', 'Progrès adoption'), ('social_update', 'Mise à jour sociale'), ('social_note_added', 'Note sociale ajoutée'), ('home_visit', 'Visite domicile'), ('counseling_session', 'Session counseling'), ('incident_reported', 'Incident signalé'), ('protection_concern', 'Préoccupation protection'), ('status_change', 'Changement de statut'), ('alert_triggered', 'Alerte déclenchée'), ('note_added', 'Note ajoutée'), ('case_note', 'Note de suivi'), ('file_downloaded', 'Fichier téléchargé'), ('record_approved', 'Enregistrement approuvé'), ('record_rejected', 'Enregistrement rejeté'), ('notification_sent', 'Notification envoyée'), ('child_archived', 'Enfant archivé'), ('child_restored', 'Enfant restauré'), ('follow_up', 'Action de suivi'), ('observation_added', 'Observation ajoutée'), ('transfer_initiated', 'Transfert initié'), ('exit_registered', 'Sortie enregistrée')], max_length=30, verbose_name="Type d'événement"),
        ),
        migrations.AddIndex(
            model_name='childhistory',
            index=models.Index(fields=['child', '-event_date'], name='children_ch_child_i_df332e_idx'),
        ),
        migrations.AddIndex(
            model_name='childhistory',
            index=models.Index(fields=['child', 'category'], name='children_ch_child_i_03b343_idx'),
        ),
        migrations.AddIndex(
            model_name='childhistory',
            index=models.Index(fields=['child', 'event_type'], name='children_ch_child_i_025621_idx'),
        ),
        migrations.AddIndex(
            model_name='childhistory',
            index=models.Index(fields=['child', 'priority'], name='children_ch_child_i_8f36c5_idx'),
        ),
    ]
