# Generated by Django 4.2.30 on 2026-06-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanages', '0001_initial'),
        ('children', '0004_child_status_childhistory_linked_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='orphanage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='orphanages.orphanage', verbose_name='Orphelinat'),
        ),
    ]
