# Generated by Django 4.2.30 on 2026-06-29 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0005_child_orphanage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigné le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('ambassador', models.ForeignKey(limit_choices_to={'role': 'ambassador'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_children', to=settings.AUTH_USER_MODEL, verbose_name='Ambassadeur')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='children.child', verbose_name='Enfant')),
            ],
            options={
                'verbose_name': "Assignation d'enfant",
                'verbose_name_plural': "Assignations d'enfants",
                'ordering': ['-assigned_at'],
                'unique_together': {('child', 'ambassador')},
            },
        ),
    ]
