# Generated by Django 4.2.30 on 2026-07-01 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0006_childassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('filtre_applique', models.JSONField(blank=True, default=dict, verbose_name='Filtre appliqué')),
            ],
            options={
                'verbose_name': "Consultation d'historique",
                'verbose_name_plural': "Consultations d'historique",
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='FichierJoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='historique/', verbose_name='Fichier')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('taille', models.IntegerField(default=0, verbose_name='Taille (octets)')),
                ('type_mime', models.CharField(blank=True, default='', max_length=100, verbose_name='Type MIME')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Téléversé le')),
            ],
            options={
                'verbose_name': 'Fichier joint',
                'verbose_name_plural': 'Fichiers joints',
            },
        ),
        migrations.AlterModelOptions(
            name='childhistory',
            options={'ordering': ['-event_date'], 'permissions': [('validate_history', "Peut valider/rejeter des événements d'historique"), ('view_confidential_history', 'Peut voir les événements confidentiels'), ('view_consultation_log', 'Peut voir le journal des consultations')], 'verbose_name': 'Historique enfant', 'verbose_name_plural': 'Historiques enfants'},
        ),
        migrations.AddField(
            model_name='childhistory',
            name='evenement_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='children.childhistory', verbose_name='Événement parent'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='hash_courant',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash courant'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='hash_precedent',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash précédent'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='niveau_sensibilite',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTREINT', 'Restreint'), ('CONFIDENTIEL', 'Confidentiel')], default='PUBLIC', max_length=20, verbose_name='Niveau de sensibilité'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='statut_validation',
            field=models.CharField(choices=[('AUTO_VALIDE', 'Auto-validé'), ('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='AUTO_VALIDE', max_length=20, verbose_name='Statut de validation'),
        ),
        migrations.AddIndex(
            model_name='childhistory',
            index=models.Index(fields=['child', 'statut_validation'], name='children_ch_child_i_01d5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='childhistory',
            index=models.Index(fields=['child', 'niveau_sensibilite'], name='children_ch_child_i_68ccb3_idx'),
        ),
        migrations.AddField(
            model_name='fichierjoint',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Téléversé par'),
        ),
        migrations.AddField(
            model_name='consultationhistorique',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_historique', to='children.child', verbose_name='Enfant'),
        ),
        migrations.AddField(
            model_name='consultationhistorique',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_historique', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='childhistory',
            name='piece_jointe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='children.fichierjoint', verbose_name='Pièce jointe'),
        ),
        migrations.AddIndex(
            model_name='consultationhistorique',
            index=models.Index(fields=['utilisateur', '-horodatage'], name='children_co_utilisa_5d69b3_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationhistorique',
            index=models.Index(fields=['enfant', '-horodatage'], name='children_co_enfant__86334a_idx'),
        ),
    ]
