# Generated by Django 4.2.30 on 2026-07-04 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0007_consultationhistorique_fichierjoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childhistory',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='children.child', verbose_name='Enfant'),
        ),
    ]
