# Generated by Django 4.2.30 on 2026-07-08 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0008_alter_childhistory_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='biography',
            field=models.TextField(blank=True, default='', verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='child',
            name='dream',
            field=models.TextField(blank=True, default='', verbose_name='Rêve'),
        ),
        migrations.AddField(
            model_name='child',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_children', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='child',
            name='interests',
            field=models.JSONField(blank=True, default=list, verbose_name="Centres d'intérêt"),
        ),
        migrations.AddField(
            model_name='child',
            name='medical_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='Informations médicales'),
        ),
        migrations.AddField(
            model_name='child',
            name='school_level',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Niveau scolaire'),
        ),
        migrations.AddField(
            model_name='child',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Nom de l'école"),
        ),
        migrations.AddField(
            model_name='child',
            name='school_progress',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Progrès scolaire'),
        ),
        migrations.AddField(
            model_name='child',
            name='skills',
            field=models.JSONField(blank=True, default=list, verbose_name='Talents'),
        ),
    ]
