# Generated by Django 4.2.30 on 2026-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0009_child_biography_child_dream_child_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childupdate',
            name='category',
            field=models.CharField(choices=[('health', 'Santé'), ('education', 'Éducation'), ('family', 'Famille'), ('documents', 'Documents'), ('social', 'Social'), ('food', 'Nourriture'), ('clothing', 'Vêtements'), ('emergency', 'Urgence'), ('progress', 'Progrès général')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
