# Generated by Django 4.2.30 on 2026-07-02 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0007_consultationhistorique_fichierjoint_and_more'),
        ('orphanages', '0008_orphanagedocument_points_to_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('enfant', 'Pour un enfant'), ('orphelinat', 'Pour un orphelinat'), ('federation', 'Pour la fédération')], max_length=20, verbose_name='Type')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('resume', models.CharField(blank=True, max_length=255, verbose_name='Résumé')),
                ('createur_role', models.CharField(choices=[('directeur', 'Directeur'), ('ambassadeur', 'Ambassadeur'), ('federation', 'Federation')], max_length=20, verbose_name='Rôle du créateur')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis_validation', 'Soumis Validation'), ('modification_demandee', 'Modification Demandee'), ('rejete', 'Rejete'), ('publie', 'Publie'), ('en_financement', 'En Financement'), ('finance', 'Finance'), ('cloture', 'Cloture'), ('suspendu', 'Suspendu')], default='brouillon', max_length=30, verbose_name='Statut')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('commentaire_modification', models.TextField(blank=True, verbose_name='Commentaire de modification')),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Budget total')),
                ('montant_collecte', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant collecté')),
                ('beneficiaires', models.IntegerField(default=0, verbose_name='Bénéficiaires')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('documents', models.JSONField(blank=True, default=dict, verbose_name='Documents')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='projets/', verbose_name='Fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('ambassadeur_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('enfant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='children.child', verbose_name='Enfant')),
                ('orphelinat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='orphanages.orphanage', verbose_name='Orphelinat')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('projet_cree', 'Projet Cree'), ('projet_soumis', 'Projet Soumis'), ('projet_valide', 'Projet Valide'), ('projet_rejete', 'Projet Rejete'), ('modification_demandee', 'Modification Demandee'), ('projet_modifie', 'Projet Modifie'), ('projet_suspendu', 'Projet Suspendu'), ('projet_reactive', 'Projet Reactive'), ('candidature_soumise', 'Candidature Soumise'), ('candidature_acceptee', 'Candidature Acceptee'), ('candidature_refusee', 'Candidature Refusee'), ('projet_finance', 'Projet Finance'), ('projet_cloture', 'Projet Cloture')], max_length=30, verbose_name="Type d'événement")),
                ('statut_avant', models.CharField(blank=True, max_length=30, verbose_name='Statut avant')),
                ('statut_apres', models.CharField(blank=True, max_length=30, verbose_name='Statut après')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_projets', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='projets.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Événement de projet',
                'verbose_name_plural': 'Événements de projet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidatureProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_propose', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant proposé')),
                ('modalite', models.CharField(choices=[('unique', 'Unique'), ('echelonne', 'Echelonne')], default='unique', max_length=20, verbose_name='Modalité')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('statut', models.CharField(choices=[('en_attente_reponse', 'En Attente'), ('acceptee', 'Acceptee'), ('refusee', 'Refusee')], default='en_attente_reponse', max_length=30, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Candidature le')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures_projets', to=settings.AUTH_USER_MODEL, verbose_name='Partenaire')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='projets.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
                'unique_together': {('projet', 'partenaire')},
            },
        ),
    ]
