# Generated by Django 4.2.30 on 2026-06-24 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('enfant', 'Pour un enfant'), ('orphelinat', "Pour l'orphelinat"), ('federation', 'Pour la fédération')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Résumé')),
                ('description', models.TextField(verbose_name='Description')),
                ('pdf_url', models.TextField(blank=True, verbose_name='PDF (base64 ou URL)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='projets/', verbose_name='Fichier PDF')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('funded', 'Financé'), ('completed', 'Terminé')], default='open', max_length=20, verbose_name='Statut')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Budget')),
                ('raised', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Collecté')),
                ('beneficiaries', models.IntegerField(default=0, verbose_name='Bénéficiaires')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Candidature le')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projets.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'applicant')},
            },
        ),
    ]
