# Generated by Django 4.2.30 on 2026-07-08 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projets', '0001_initial_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
    ]
