# Generated by Django 4.2.30 on 2026-07-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0010_alter_childupdate_category'),
        ('projets', '0002_project_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_generes', to='children.childupdate', verbose_name="Mise à jour d'origine"),
        ),
    ]
