# Generated by Django 4.2.30 on 2026-07-14 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projets', '0003_project_source_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_a_reviser', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='project',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis_validation', 'Soumis Validation'), ('en_attente_ambassadeur', 'En Attente Ambassadeur'), ('en_attente_federation', 'En Attente Federation'), ('modification_demandee', 'Modification Demandee'), ('rejete', 'Rejete'), ('approuve', 'Approuve'), ('publie', 'Publie'), ('en_financement', 'En Financement'), ('finance', 'Finance'), ('cloture', 'Cloture'), ('suspendu', 'Suspendu')], default='brouillon', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='projethistory',
            name='type_evenement',
            field=models.CharField(choices=[('projet_cree', 'Projet Cree'), ('projet_soumis', 'Projet Soumis'), ('projet_attribue_ambassadeur', 'Projet Attribue Ambassadeur'), ('projet_attribue_federation', 'Projet Attribue Federation'), ('projet_valide', 'Projet Valide'), ('projet_approuve', 'Projet Approuve'), ('projet_rejete', 'Projet Rejete'), ('modification_demandee', 'Modification Demandee'), ('projet_modifie', 'Projet Modifie'), ('projet_resoumis', 'Projet Resoumis'), ('projet_suspendu', 'Projet Suspendu'), ('projet_reactive', 'Projet Reactive'), ('candidature_soumise', 'Candidature Soumise'), ('candidature_acceptee', 'Candidature Acceptee'), ('candidature_refusee', 'Candidature Refusee'), ('projet_finance', 'Projet Finance'), ('projet_cloture', 'Projet Cloture')], max_length=30, verbose_name="Type d'événement"),
        ),
    ]
