# Generated by Django 4.2.30 on 2026-07-16 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projets', '0004_projet_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatureprojet',
            name='commentaire_reponse',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire du répondant'),
        ),
        migrations.AddField(
            model_name='candidatureprojet',
            name='repondu_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Répondu le'),
        ),
        migrations.AddField(
            model_name='candidatureprojet',
            name='repondu_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Répondu par'),
        ),
        migrations.AddField(
            model_name='candidatureprojet',
            name='type_financement',
            field=models.CharField(choices=[('total', 'Financement total'), ('partiel', 'Financement partiel')], default='partiel', max_length=20, verbose_name='Type de financement'),
        ),
        migrations.AddField(
            model_name='candidatureprojet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='candidatureprojet',
            name='statut',
            field=models.CharField(choices=[('en_attente_reponse', 'En Attente'), ('acceptee', 'Acceptee'), ('refusee', 'Refusee'), ('amelioration_demandee', 'Amelioration')], default='en_attente_reponse', max_length=30, verbose_name='Statut'),
        ),
    ]
