# Generated by Django 4.2.30 on 2026-07-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_project_code_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amelioration_fichier',
            field=models.FileField(blank=True, null=True, upload_to='projets/ameliorations/', verbose_name="Fichier joint à la demande d'amélioration"),
        ),
    ]
