# Generated by Django 6.1 on 2026-08-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0007_amelioration_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projethistory',
            name='type_evenement',
            field=models.CharField(choices=[('projet_cree', 'Projet Cree'), ('projet_soumis', 'Projet Soumis'), ('projet_attribue_ambassadeur', 'Projet Attribue Ambassadeur'), ('projet_attribue_federation', 'Projet Attribue Federation'), ('projet_valide', 'Projet Valide'), ('projet_approuve', 'Projet Approuve'), ('projet_rejete', 'Projet Rejete'), ('modification_demandee', 'Modification Demandee'), ('projet_modifie', 'Projet Modifie'), ('projet_resoumis', 'Projet Resoumis'), ('projet_suspendu', 'Projet Suspendu'), ('projet_reactive', 'Projet Reactive'), ('candidature_soumise', 'Candidature Soumise'), ('candidature_acceptee', 'Candidature Acceptee'), ('candidature_refusee', 'Candidature Refusee'), ('candidature_amelioration', 'Candidature Amelioration'), ('candidature_resoumise', 'Candidature Resoumise'), ('projet_finance', 'Projet Finance'), ('projet_cloture', 'Projet Cloture')], max_length=30, verbose_name="Type d'événement"),
        ),
    ]
