# Generated by Django 4.2.30 on 2026-06-24 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orphanages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du besoin')),
                ('category', models.CharField(choices=[('alimentation', 'Alimentation'), ('sante', 'Santé'), ('education', 'Éducation'), ('infrastructures', 'Infrastructures'), ('energie', 'Énergie'), ('eau', 'Eau')], max_length=50, verbose_name='Catégorie')),
                ('priority', models.CharField(choices=[('critique', 'Urgence critique'), ('haute', 'Haute priorité'), ('moyenne', 'Priorité moyenne'), ('faible', 'Faible priorité')], max_length=20, verbose_name='Priorité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='Quantité (ex: 50 kg, 2 boîtes)')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('fulfilled', 'Comblé')], default='open', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='orphanages.orphanage', verbose_name='Orphelinat')),
            ],
            options={
                'verbose_name': 'Besoin',
                'verbose_name_plural': 'Besoins',
            },
        ),
    ]
